- name: Install and configure MariaDB
  hosts: all
  tasks:
    - name: Install MariaDB client
      apt:
        name: mariadb-client
        state: present

    - name: Wait for MySQL container to be ready
      wait_for:
        host: 127.0.0.1
        port: 3306
        timeout: 30

    - name: Secure MariaDB installation
      mysql_user:
        login_host: 127.0.0.1
        login_user: root
        login_password: root
        name: root
        password: your_root_password
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: Create a new database
      mysql_db:
        login_host: 127.0.0.1
        login_user: root
        login_password: your_root_password
        name: mydatabase
        state: present

    - name: Create a database user with privileges
      mysql_user:
        login_host: 127.0.0.1
        login_user: root
        login_password: your_root_password
        name: myuser
        password: mypassword
        priv: 'mydatabase.*:ALL'
        host: '%'
        state: present
